INSERT INTO destinations (country, city_state, climate) VALUES ('US', 'Miami, FL', 'warm')
INSERT INTO destinations (country, city_state, climate) VALUES ('US', 'Santa Monica, CA', 'warm')
INSERT INTO destinations (country, city_state, climate) VALUES ('US', 'Puerto Rico', 'warn')
INSERT INTO destinations (country, city_state, climate) VALUES ('US', 'Alaska', 'cold')
INSERT INTO destinations (country, city_state, climate) VALUES ('South Africa,' 'Cape Town', 'seasonal')